modLoader="javafml"
loaderVersion="[28,)"
authors="maxwell_lt"
[[mods]]
modId="titlechanger"
version="${file.jarVersion}"
displayName="TitleChanger"
description='''
Changes the Minecraft window title.
'''
issueTrackerURL="https://github.com/Maxwell-lt/TitleChanger/issues"
updateJSONURL="https://raw.githubusercontent.com/Maxwell-lt/TitleChanger/master/update.json"
[[dependencies.titlechanger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"